/*
studioDB.mysql by Tony Matts

Creates 13 tables for a music studio database.

Foreign Key -> Primary Key: 
ENGINEER_B.EngNum -> ENGINEER_A.EngNum
RECORDING_MACHINE_B.Rserial -> RECORDING_MACHINE_A.Rserial
MASTER_COPY_A.RecordCo -> RECORDING_CO.RcName
MASTER_COPY_B.AlbumCode -> MASTER_COPY_A.AlbumCode
*/
CREATE TABLE PRODUCER ( 
	Pnum			INT				NOT NULL	AUTO_INCREMENT,
	ActiveSince		VARCHAR(10),
	Pname			VARCHAR(50)		NOT NULL,
	PRIMARY KEY(Pnum)
)ENGINE = InnoDB;

CREATE TABLE MUSICIAN (
	Nnum			INT				NOT NULL	AUTO_INCREMENT,
	Mname  			VARCHAR(50)  	NOT NULL,
	Mgroup 			VARCHAR(75)  	NOT NULL,
  	Competency  	INT 			NOT NULL,
  	Pnum			INT,			
  	PRIMARY KEY(Mnum),
  	FOREIGN KEY(Pnum) REFERENCES PRODUCER(Pnum)
)ENGINE = InnoDB;

CREATE TABLE INSTRUMENT (
	Iserial 		VARCHAR(50) 	NOT NULL,
	Ibrand		 	VARCHAR(30)		NOT NULL,
	Imodel	 		VARCHAR(30),
	PRIMARY KEY(Iserial)
)ENGINE = InnoDB;

CREATE TABLE STUDIO_TECH (
  	Snum  	  		INT				NOT NULL	AUTO_INCREMENT,
  	Sname  			VARCHAR(50)		NOT NULL,
  	Hours  			DOUBLE,
  	Payrate  		DOUBLE		  	NOT NULL,
  	PRIMARY KEY(Snum)
)ENGINE = InnoDB;

CREATE TABLE EFFECT (
	Eserial 		VARCHAR(50) 	NOT NULL,
	Jacks  			INT,
	Emodel 			VARCHAR(50),
	Watts			INT,
	PRIMARY KEY(Eserial)
)ENGINE = InnoDB;

CREATE TABLE MIXER (
	Mserial			VARCHAR(50) 	NOT NULL,
	Channels		INT				NOT NULL,
	Tracks			INT				NOT NULL,
	PRIMARY KEY(Mserial)
)ENGINE = InnoDB;

CREATE TABLE ENGINEER_A (
	EngNum			INT				NOT NULL	AUTO_INCREMENT,
	EngName 		VARCHAR(50) 	NOT NULL,
	NumOfAlbums		INT				NOT NULL,	
	PRIMARY KEY(EngNum)
)ENGINE = InnoDB;

CREATE TABLE ENGINEER_B (
	EngNum			INT				NOT NULL	AUTO_INCREMENT,
	Degree 			VARCHAR(50) 	NOT NULL,	
	PRIMARY KEY(EngNum, Degree),
	FOREIGN KEY(EngNum) REFERENCES ENGINEER_A(EngNum)
)ENGINE = InnoDB;

CREATE TABLE RECORDING_MACHINE_A (
	Rserial 		VARCHAR(30)		NOT NULL,
	Os  			VARCHAR(30) 	NOT NULL,
	PRIMARY KEY(Rserial)
)ENGINE = InnoDB;

CREATE TABLE RECORDING_MACHINE_B (
	Rserial 		VARCHAR(30)		NOT NULL,
	Software  		VARCHAR(30) 	NOT NULL,
	Version			VARCHAR(10)		NOT NULL,
	PRIMARY KEY(Rserial, Software),
	FOREIGN KEY(Rserial) REFERENCES RECORDING_MACHINE_A(Rserial)
)ENGINE = InnoDB;

CREATE TABLE RECORD_CO (
	RcName			VARCHAR(50)		NOT NULL,
	Rate 			DOUBLE			NOT NULL,
	Balance			DOUBLE			NOT NULL,
	PRIMARY KEY(RcName)
)ENGINE = InnoDB;

CREATE TABLE MASTER_COPY_A (
	AlbumCode		INT				NOT NULL	AUTO_INCREMENT,
	Title			VARCHAR(70)		NOT NULL,
	RcName			VARCHAR(50),
	PRIMARY KEY(AlbumCode),
	FOREIGN KEY(RcName) REFERENCES RECORD_CO(RcName)
)ENGINE = InnoDB;

CREATE TABLE MASTER_COPY_B (
	AlbumCode		INT				NOT NULL	AUTO_INCREMENT,
	Crew			VARCHAR(50)	NOT NULL,
	PRIMARY KEY(AlbumCode, Crew),
	FOREIGN KEY(AlbumCode) REFERENCES MASTER_COPY_A(AlbumCode)
)ENGINE = InnoDB;