# ecoliAnalysis.R by Tony Matts
# Gene Expression Project
# CSCI 451
# Fall '13
# R source file for read a csv file generated by genExp.pl

#load the data into a data frame
diffExpMatrix = read.csv("ecoliDifferentialExp.csv")
#convert it to a matrix
diffExpMatrix = data.matrix(diffExpMatrix)

#clusters = flashClust(DIFF)
#heatmap(DIFF,Rowv = as.dendrogram(clusters),margins = c(6,6))

#perform hierarchical clustering
clusters = hclust(diffExpMatrix)
plot(clusters)

memb = cutree(clusters, k = 16) #indicate how many clusters
par(mfrow = c(4,4)) #set the parameters of the figure

#create 16 sub plots and populate them with line-plots
curCluster = 0;
for(Xcell in 1:4){
  for(Ycell in 1:4){
    curCluster = curCluster + 1
    rows = which(memb==curCluster) 
    numInCluster = length(rows)
    xvals = c(0:(numInCluster*4-1))
    xvals = xvals %%4+1
    xvals = matrix(xvals,ncol=4,byrow=TRUE)
   
    for(k in 1:numInCluster){
      par(mfg=c(Xcell,Ycell))
      plot(xvals[k,],diffExpMatrix[rows[k],])
      lines(xvals[k,],diffExpMatrix[rows[k],])
    }
  }
}

pc = prcomp(diffExpMatrix)
